version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: flight_db
    environment:
      POSTGRES_USER: flight_user
      POSTGRES_PASSWORD: flight_password
      POSTGRES_DB: flight_schedule
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/1_init_schema.sql
      # Тестовые данные
      - ./db/test_data.sql:/docker-entrypoint-initdb.d/2_test_data.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flight_network

  backend:
    build:
      context: ./backend      
    container_name: flight_backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/static
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: flight_user
      DB_PASS: flight_password
      DB_NAME: flight_schedule
    networks:
      - flight_network

volumes:
  db_data:

networks:
  flight_network: